### ISSUE TITLE
db lock on push

### ISSUE THREAD

**Issue by ahdinosaur** [ahdinosaur/pub.dinosaur.is#1]
```
=====> pub container output:
       > pub.dinosaur.is@1.0.0 start /app
       > sbot server --port $PORT
       events.js:141
             throw er; // Unhandled 'error' event
             ^
       OpenError: IO error: lock /app/data/db/LOCK: Resource temporarily unavailable
           at /app/node_modules/level-packager/node_modules/levelup/lib/levelup.js:119:34
           at /app/node_modules/leveldown/node_modules/abstract-leveldown/abstract-leveldown.js:39:16
       npm ERR! Linux 3.13.0-68-generic
       npm ERR! argv "/app/.heroku/node/bin/node" "/app/.heroku/node/bin/npm" "start"
       npm ERR! node v4.2.3
       npm ERR! npm  v3.5.1
       npm ERR! code ELIFECYCLE
       npm ERR! pub.dinosaur.is@1.0.0 start: `sbot server --port $PORT`
       npm ERR! Exit status 1
       npm ERR! 
       npm ERR! Failed at the pub.dinosaur.is@1.0.0 start script 'sbot server --port $PORT'.
       npm ERR! Make sure you have the latest version of node.js and npm installed.
       npm ERR! If you do, this is most likely a problem with the pub.dinosaur.is package,
       npm ERR! not with npm itself.
       npm ERR! Tell the author that this fails on your system:
       npm ERR!     sbot server --port $PORT
       npm ERR! You can get information on how to open an issue for this project with:
       npm ERR!     npm bugs pub.dinosaur.is
       npm ERR! Or if that isn't available, you can get their info via:
       npm ERR!     npm owner ls pub.dinosaur.is
       npm ERR! There is likely additional logging output above.
       npm ERR! Please include the following file with any support request:
       npm ERR!     /app/npm-debug.log
=====> end pub container output
```

**Comment by ahdinosaur** [comment]
fix is to `dokku ps:stop pub` then push, or if already pushed then `dokku ps:stop pub && dokku ps:start pub`, not great but works for now.
